spring:
  config:
    import: classpath:api.properties
  application:
    name: "ort"
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            provider: kakao
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - talk_message
              - talk_calendar
              - talk_calendar_task
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id